# Generated by Django 4.1.4 on 2024-02-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('designation', models.CharField(max_length=30, null=True)),
                ('department', models.CharField(max_length=40)),
                ('doj', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
